---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-pi-with-timeout
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 30
  template:
    spec:
      containers:
      - name: job-pi-with-timeout
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
---
