---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-pi-with-ttl
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: job-pi-with-ttl
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
---
